#! /bin/sh
# update & upgrade
printf "Running system upgrade...\n"
sudo apt-get update
sudo apt-get upgrade

printf "Installing dialogs"
sudo apt-get install dialog


# install maven and Mysql
dialog --title "Confirmation Required" --yesno "This will install the following required packages:\n * maven\n * mysql-server\n\nContinue?" 10 40
if [ $? != 0 ]; then
	dialog --infobox "Installation aborted" 5 20
	sleep 3
	dialog --clear
	clear
	exit 0
fi
sudo apt-get install maven
sudo apt-get install mysql-server
sudo mysql_secure_installation

# log in to mysql db
mysql -u root -p < avatar_webchat_db.sql

# create database avatar_webchat;
# grant all on avatar_webchat.* to 'avatar_admin' identified by 'avatarTeam!2'
