#! /bin/sh
# update & upgrade
sudo apt-get update
sudo apt-get upgrade

# install maven and Mysql
sudo apt-get install maven
sudo apt-get install mysql-server
sudo mysql_secure_installation
sudo mysqld --initialize


# log in to mysql db
service mysqld restart
mysql -u root -p < avatar_webchat_db.sql

# create database avatar_webchat;
# grant all on avatar_webchat.* to 'avatar_admin' identified by 'avatarTeam!2';


